### ISSUE TITLE
Invalid card is recognized as American Express

### ISSUE THREAD

**Issue by kakarotto67** [Romanone/KottansCardChecker#1]
Pass "3434343434343433" into your GetCreditCardVendor method.
Expected result: unknown as this card isn't valid (even your IsCreditCardNumberValid method returns false)
Actual result: "American Express"

**Comment by kakarotto67** [comment]
Similar issue with "41111111111111112":
IsCreditCardNumberValid returns false (which is correct), but GetCreditCardVendor returns VISA (which is incorrect)

**Comment by kakarotto67** [comment]
And the same issue with "50000000000006114": it is invalid, but returns Maestro.

**Comment by kakarotto67** [comment]
Number "50000000000006114" is still recognized as Maestro, but should be unknown as it is invalid.

**Comment by Romanone** [comment]
Done.
