### ISSUE TITLE
Invalid card number recognized as JCB

### ISSUE THREAD

**Issue by kakarotto67** [Romanone/KottansCardChecker#2]
Pass "35301113333000001" into GetCreditCardVendor method
Expected result: invalid number (17 characters, but JCB allows 16 only)
Actual result: JCB

**Comment by kakarotto67** [comment]
I still have this issue: true is returned when I pass "35301113333000001" into IsCreditCardNumberValid method, but should be false.

**Comment by Romanone** [comment]
Done.
