### ISSUE TITLE
GenerateNextCreditCardNumber generates incorrect card number

### ISSUE THREAD

**Issue by kakarotto67** [Romanone/KottansCardChecker#3]
Pass "4999999999999999993" into GenerateNextCreditCardNumber method
Expected: no more numbers left for VISA
Actual: some random numbers when we expect the **next** one

**Comment by kakarotto67** [comment]
Your GenerateNextCreditCardNumber method generates some random numbers every time I pass the same input, but not the next number. A few more tests crash due to this.

**Comment by Romanone** [comment]
Done.
